server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./data/todolist.db
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 文件上传配置
file:
  upload:
    path: ./uploads/
    
# 跨域配置
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  
logging:
  level:
    com.todolist: DEBUG
    org.springframework.jdbc: DEBUG
